// ============================================================
// 픽천국 국가명 한글 매핑 테이블 (COUNTRY_MAP)
// all-fixtures.json 기준 158개 국가 전체 수록
// key: API에서 오는 country 필드값 (대소문자 정확히)
// value: 한글 표기
// ============================================================

const COUNTRY_MAP = {

  // ===== 아시아 =====
  'Asia': '아시아',
  'South Korea': '대한민국',
  'South-Korea': '대한민국',
  'Japan': '일본',
  'China': '중국',
  'Chinese-Taipei': '대만',
  'Taiwan': '대만',
  'Hong-Kong': '홍콩',
  'Macao': '마카오',
  'Thailand': '태국',
  'Vietnam': '베트남',
  'Indonesia': '인도네시아',
  'Malaysia': '말레이시아',
  'Philippines': '필리핀',
  'Singapore': '싱가포르',
  'Cambodia': '캄보디아',
  'India': '인도',
  'Bangladesh': '방글라데시',
  'Bhutan': '부탄',
  'Mongolia': '몽골',
  'Iran': '이란',
  'Iraq': '이라크',
  'Jordan': '요르단',
  'Kuwait': '쿠웨이트',
  'Bahrain': '바레인',
  'Qatar': '카타르',
  'Oman': '오만',
  'Saudi-Arabia': '사우디아라비아',
  'United-Arab-Emirates': '아랍에미리트',
  'Lebanon': '레바논',
  'Syria': '시리아',
  'Israel': '이스라엘',
  'Kazakhstan': '카자흐스탄',
  'Uzbekistan': '우즈베키스탄',
  'Kyrgyzstan': '키르기스스탄',
  'Tajikistan': '타지키스탄',
  'Turkmenistan': '투르크메니스탄',
  'Azerbaijan': '아제르바이잔',
  'Armenia': '아르메니아',
  'Georgia': '조지아',

  // ===== 유럽 =====
  'Europe': '유럽',
  'England': '잉글랜드',
  'Scotland': '스코틀랜드',
  'Wales': '웨일스',
  'Northern-Ireland': '북아일랜드',
  'Ireland': '아일랜드',
  'United Kingdom': '영국',
  'United-Kingdom': '영국',
  'France': '프랑스',
  'Germany': '독일',
  'Spain': '스페인',
  'Italy': '이탈리아',
  'Portugal': '포르투갈',
  'Netherlands': '네덜란드',
  'Belgium': '벨기에',
  'Switzerland': '스위스',
  'Austria': '오스트리아',
  'Sweden': '스웨덴',
  'Norway': '노르웨이',
  'Denmark': '덴마크',
  'Finland': '핀란드',
  'Iceland': '아이슬란드',
  'Faroe-Islands': '페로 제도',
  'Poland': '폴란드',
  'Czech Republic': '체코',
  'Czech-Republic': '체코',
  'Slovakia': '슬로바키아',
  'Hungary': '헝가리',
  'Romania': '루마니아',
  'Bulgaria': '불가리아',
  'Greece': '그리스',
  'Croatia': '크로아티아',
  'Serbia': '세르비아',
  'Slovenia': '슬로베니아',
  'Bosnia': '보스니아',
  'Bosnia-and-Herzegovina': '보스니아 헤르체고비나',
  'Montenegro': '몬테네그로',
  'Kosovo': '코소보',
  'Albania': '알바니아',
  'Macedonia': '북마케도니아',
  'Russia': '러시아',
  'Ukraine': '우크라이나',
  'Belarus': '벨라루스',
  'Moldova': '몰도바',
  'Estonia': '에스토니아',
  'Latvia': '라트비아',
  'Lithuania': '리투아니아',
  'Luxembourg': '룩셈부르크',
  'Andorra': '안도라',
  'San-Marino': '산마리노',
  'Liechtenstein': '리히텐슈타인',
  'Malta': '몰타',
  'Cyprus': '키프로스',
  'Turkey': '튀르키예',

  // ===== 아메리카 =====
  'USA': '미국',
  'Canada': '캐나다',
  'Mexico': '멕시코',
  'Brazil': '브라질',
  'Argentina': '아르헨티나',
  'Colombia': '콜롬비아',
  'Chile': '칠레',
  'Peru': '페루',
  'Ecuador': '에콰도르',
  'Venezuela': '베네수엘라',
  'Uruguay': '우루과이',
  'Paraguay': '파라과이',
  'Bolivia': '볼리비아',
  'Costa-Rica': '코스타리카',
  'Guatemala': '과테말라',
  'Honduras': '온두라스',
  'El-Salvador': '엘살바도르',
  'Nicaragua': '니카라과',
  'Panama': '파나마',
  'Cuba': '쿠바',
  'Jamaica': '자메이카',
  'Dominican-Republic': '도미니카 공화국',
  'Puerto Rico': '푸에르토리코',
  'Aruba': '아루바',
  'Antigua-And-Barbuda': '앤티가 바부다',
  'Barbados': '바베이도스',
  'Suriname': '수리남',

  // ===== 아프리카 =====
  'Africa': '아프리카',
  "Cape Verde Islands": "카보베르데",
  "Cape Verde": "카보베르데",
  'Morocco': '모로코',
  'Algeria': '알제리',
  'Tunisia': '튀니지',
  'Egypt': '이집트',
  'Ghana': '가나',
  'Nigeria': '나이지리아',
  'Senegal': '세네갈',
  'Ivory-Coast': '코트디부아르',
  'Cameroon': '카메룬',
  'South-Africa': '남아프리카공화국',
  'Kenya': '케냐',
  'Uganda': '우간다',
  'Tanzania': '탄자니아',
  'Rwanda': '르완다',
  'Ethiopia': '에티오피아',
  'Sudan': '수단',
  'Angola': '앙골라',
  'Zambia': '잠비아',
  'Zimbabwe': '짐바브웨',
  'Botswana': '보츠와나',
  'Lesotho': '레소토',
  'Eswatini': '에스와티니',
  'Malawi': '말라위',
  'Mozambique': '모잠비크',
  'Mali': '말리',
  'Burkina-Faso': '부르키나파소',
  'Benin': '베냉',
  'Gabon': '가봉',
  'Congo-DR': '콩고 민주공화국',
  'D.R. Congo': '콩고 민주공화국',
  'Liberia': '라이베리아',
  'Gambia': '감비아',
  'Mauritania': '모리타니',
  'Burundi': '부룬디',
  'Libya': "리비아",

  // ===== 오세아니아 =====
  'Australia': '호주',
  'New Zealand': '뉴질랜드',
  'New-Zealand': '뉴질랜드',

  // ===== 국제 =====
  'World': '국제',

};

export default COUNTRY_MAP;