// ============================================================
// 픽천국 팀명 한글 매핑 테이블 (TEAM_NAME_MAP)
// 파일의 영문 표기 → 한국인에게 익숙한 한글팀명
// ============================================================

const TEAM_NAME_MAP = {

  // ===== ⚽ 프리미어리그 (Premier League) =====
  "Leeds": "리즈 유나이티드",
  "Leeds United": "리즈 유나이티드",
  "Coventry": "코번트리 시티",
  "Ipswich": "입스위치 타운",
  "Hull City": "헐 시티",
  "Hull": "헐 시티",
  "Arsenal": "아스널",
  "Aston Villa": "아스톤 빌라",
  "Bournemouth": "본머스",
  "Brentford": "브렌트퍼드",
  "Brighton": "브라이튼",
  "Burnley": "번리",
  "Chelsea": "첼시",
  "Crystal Palace": "크리스탈 팰리스",
  "Everton": "에버턴",
  "Fulham": "풀럼",
  "Liverpool": "리버풀",
  "Manchester City": "맨시티",
  "Man City": "맨시티",
  "Manchester United": "맨체스터 유나이티드",
  "Man United": "맨체스터 유나이티드",
  "Newcastle": "뉴캐슬",
  "Nottingham Forest": "노팅엄 포레스트",
  "Nottm Forest": "노팅엄 포레스트",
  "Sunderland": "선덜랜드",
  "Tottenham": "토트넘",
  "West Ham": "웨스트햄",
  "Wolves": "울버햄튼",

  // ===== 🇪🇸 라리가 (La Liga) =====
  "Racing Santander": "레이싱 산탄데르",
  "Deportivo La Coruna": "데포르티보 라코루냐",
  "Deportivo A Coruña": "데포르티보 라코루냐",
  "Malaga": "말라가",
  "Alaves": "알라베스",
  "Athletic Club": "아틀레틱 클럽",
  "Atletico Madrid": "아틀레티코 마드리드",
  "Barcelona": "바르셀로나",
  "Celta Vigo": "셀타 비고",
  "Elche": "엘체",
  "Espanyol": "에스파뇰",
  "Getafe": "헤타페",
  "Girona": "지로나",
  "Levante": "레반테",
  "Mallorca": "마요르카",
  "Osasuna": "오사수나",
  "Rayo Vallecano": "라요 바예카노",
  "Real Betis": "레알 베티스",
  "Real Madrid": "레알 마드리드",
  "Real Sociedad": "레알 소시에다드",
  "Sevilla": "세비야",
  "Valencia": "발렌시아",
  "Villarreal": "비야레알",

  // ===== 🇩🇪 분데스리가 (Bundesliga) =====
  "Hamburger SV": "함부르크",
  "SV Elversberg": "엘버스베르크",
  "FC Schalke 04": "샬케 04",
  "Schalke 04": "샬케 04",
  "SC Paderborn 07": "파더보른",
  "1. FC Heidenheim": "하이덴하임",
  "FC Heidenheim": "하이덴하임",
  "1. FC Köln": "쾰른",
  "1899 Hoffenheim": "호펜하임",
  "Hoffenheim": "호펜하임",
  "Bayer Leverkusen": "바이어 레버쿠젠",
  "Leverkusen": "바이어 레버쿠젠",
  "Bayern München": "바이에른 뮌헨",
  "Borussia Dortmund": "보루시아 도르트문트",
  "Dortmund": "보루시아 도르트문트",
  "Borussia Mönchengladbach": "보루시아 묀헨글라트바흐",
  "M'gladbach": "보루시아 묀헨글라트바흐",
  "Eintracht Frankfurt": "아인트라흐트 프랑크푸르트",
  "FC Augsburg": "아우크스부르크",
  "FC St. Pauli": "장크트 파울리",
  "St. Pauli": "장크트 파울리",
  "FSV Mainz 05": "마인츠 05",
  "RB Leipzig": "RB 라이프치히",
  "SC Freiburg": "프라이부르크",
  "Freiburg": "프라이부르크",
  "Union Berlin": "우니온 베를린",
  "VfB Stuttgart": "슈투트가르트",
  "VfL Wolfsburg": "볼프스부르크",
  "Wolfsburg": "볼프스부르크",
  "Werder Bremen": "베르더 브레멘",

  // ===== 🇦🇹 오스트리아 분데스리가 (Austrian Bundesliga) =====
  // ⚠️ 오스트리아 분데스리가는 독일 분데스리가와 이름만 같을 뿐 별개 리그입니다.
  // 5대리그(독일 분데스리가) 화이트리스트에는 포함시키면 안 됩니다.
  "Austria Vienna": "아우스트리아 빈",
  "Austria Wien": "아우스트리아 빈",
  "Austria Lustenau": "SC 오스트리아 루스테나우",
  "FC BW Linz": "BW 린츠",
  "Grazer AK": "그라처 AK",
  "Lask Linz": "라스크 린츠",
  "Rapid Vienna": "라피트 빈",
  "Rapid Wien": "라피트 빈",
  "Red Bull Salzburg": "레드불 잘츠부르크",
  "Salzburg": "레드불 잘츠부르크",
  "Ried": "리트",
  "SCR Altach": "알타흐",
  "Sturm Graz": "슈투름 그라츠",
  "TSV Hartberg": "하르트베르크",
  "Hartberg": "하르트베르크",
  "WSG Wattens": "WSG 티롤",
  "WSG Tirol": "WSG 티롤",
  "Wolfsberger AC": "볼프스베르거 AC",

  // ===== 🇮🇹 세리에A (Serie A) =====
  "Cremonese": "크레모네세",
  "Venezia": "베네치아",
  "Frosinone": "프로시노네",
  "Monza": "몬차",
  "AC Milan": "AC 밀란",
  "Milan": "AC 밀란",
  "AS Roma": "AS 로마",
  "Roma": "AS 로마",
  "Atalanta": "아탈란타",
  "Bologna": "볼로냐",
  "Cagliari": "칼리아리",
  "Como": "코모",
  "Fiorentina": "피오렌티나",
  "Genoa": "제노아",
  "Hellas Verona": "엘라스 베로나",
  "Inter": "인테르",
  "Juventus": "유벤투스",
  "Lazio": "라치오",
  "Lecce": "레체",
  "Napoli": "나폴리",
  "Parma": "파르마",
  "Sassuolo": "사수올로",
  "Torino": "토리노",
  "Udinese": "우디네세",

  // ===== 🇫🇷 리그1 (Ligue 1) =====
  "Estac Troyes": "트루아",
  "Le Mans": "르망",
  "Angers": "앙제",
  "Auxerre": "옥세르",
  "Le Havre": "르아브르",
  "Lens": "랑스",
  "Lille": "릴",
  "Lorient": "로리앙",
  "Lyon": "리옹",
  "Marseille": "마르세유",
  "Metz": "메스",
  "Monaco": "모나코",
  "Nantes": "낭트",
  "Nice": "니스",
  "Paris FC": "파리 FC",
  "Paris Saint Germain": "PSG",
  "Paris Saint-Germain": "PSG",
  "PSG": "PSG", // fotmob이 UEFA Super Cup 등 일부 대회의 /matches 목록 API에서 정식명 대신
  // 이 줄임 표기를 그대로 쓰는 경우가 있어서(실사용 확인, 2026-08) 별도 키로 등록.
  "Rennes": "렌",
  "Saint Etienne": "생테티엔",
  "Saint-Etienne": "생테티엔",
  "Stade Brestois 29": "브레스트",
  "Brest": "브레스트",
  "Strasbourg": "스트라스부르",
  "Toulouse": "툴루즈",

  // ===== 🇵🇹 프리메이라리가 (Primeira Liga) =====
  "AVS": "AVS",
  "Alverca": "알베르카",
  "Arouca": "아로우카",
  "Benfica": "벤피카",
  "Casa Pia": "카사 피아",
  "Estoril": "에스토릴",
  "Estrela": "에스트렐라",
  "FC Porto": "FC 포르투",
  "Famalicao": "파말리캉",
  "GIL Vicente": "질 비센테",
  "Guimaraes": "기마랑이스",
  "Moreirense": "모레이렌스",
  "Nacional": "나시오날",
  "Rio Ave": "리우 아베",
  "SC Braga": "스포르팅 브라가",
  "Braga": "스포르팅 브라가",
  "Santa Clara": "산타 클라라",
  "Sporting CP": "스포르팅 CP",
  "Tondela": "톤델라",
  "Torreense": "토렌스",
  "Juventud": "후벤투드",
  "Atletico Torque": "몬테비데오 시티 토르케",
  "Danubio": "다누비오",
  "Wanderers": "원더러스",
  "Progreso": "프로그레소",
  

  // ===== 🇳🇱 에레디비지 (Eredivisie) =====
  "AZ Alkmaar": "AZ 알크마르",
  "Ajax": "아약스",
  "Almere City FC": "알메레 시티",
  "De Graafschap": "더 흐라프스하프",
  "Den Bosch": "덴 보스",
  "Excelsior": "엑셀시오르",
  "FC Volendam": "폴렌담",
  "Feyenoord": "페예노르트",
  "Fortuna Sittard": "포르투나 시타르트",
  "GO Ahead Eagles": "GO 어헤드 이글스",
  "Go Ahead Eagles": "GO 어헤드 이글스",
  "Groningen": "흐로닝언",
  "FC Groningen": "흐로닝언",
  "Heerenveen": "헤이렌베인",  
  "SC Heerenveen": "헤이렌베인",
  "Heracles": "헤라클레스",
  "NAC Breda": "NAC 브레다",
  "NEC Nijmegen": "NEC 네이메헌",
  "PEC Zwolle": "PEC 즈볼러",
  "PSV Eindhoven": "PSV 에인트호번",
  "Sparta Rotterdam": "스파르타 로테르담",
  "Twente": "트벤터",
  "FC Twente": "트벤터",
  "DAC 1904 Dunajska Streda": "두나이스카 스트레다",
  "Utrecht": "위트레흐트",
  "FC Utrecht": "위트레흐트",
  "Waalwijk": "발베이크",
  "Willem II": "빌럼 II",

  // ===== 🇧🇪 벨기에 (Jupiler Pro League) =====
  "Anderlecht": "안데를레흐트",
  "Antwerp": "안트베르펜",
  "Beerschot VA": "베이르스호트",
  "Cercle Brugge": "세르클 브뤼허",
  "Charleroi": "샤를루아",
  "Club Brugge KV": "클뤼프 브뤼허",
  "Dender": "덴더르",
  "Genk": "헹크",
  "Gent": "헨트",
  "KV Mechelen": "KV 메헬런",
  "KVC Westerlo": "KVC 베스털로",
  "Liège": "리에주",
  "Lommel United": "로멜 유나이티드",
  "OH Leuven": "OH 뢰번",
  "Patro Eisden": "파트로 에이스덴",
  "RAAL La Louvière": "라알 라 루비에르",
  "St. Truiden": "생트뤼던",
  "Standard Liege": "스탕다르 리에주",
  "Union St. Gilloise": "위니옹 생질루아즈",
  "Union St.Gilloise": "위니옹 생질루아즈",
  "Zulte Waregem": "쥘터 바레험",

  // ===== 🇳🇴 엘리테세리엔 (Eliteserien) =====
  "Aalesund": "올레순",
  "Bodo/Glimt": "보되/글림트",
  "Bodø/Glimt": "보되/글림트",
  "Brann": "브란",
  "Fredrikstad": "프레드릭스타드",
  "Ham-Kam": "함캄",
  "KFUM Oslo": "KFUM 오슬로",
  "Kristiansund BK": "크리스티안순",
  "Lillestrom": "릴레스트룀",
  "Molde": "몰데",
  "Rosenborg": "로젠보르",
  "Sandefjord": "산데피오르",
  "Sarpsborg 08 FF": "사르프스보르 08",
  "Start": "스타르트",
  "Tromso": "트롬쇠",
  "Tromsø": "트롬쇠",
  "Valerenga": "발레렝아",
  "Viking": "바이킹",

  // ===== 🇸🇪 알스벤스칸 (Allsvenskan) =====
  "AIK Stockholm": "AIK 스톡홀름",
  "BK Hacken": "BK 하켄",
  "Degerfors IF": "데게르포스",
  "Djurgardens IF": "유르고르덴",
  "Gais": "가이스",
  "Halmstad": "할름스타드",
  "Hammarby FF": "함마르뷔",
  "Hammarby": "함마르뷔",
  "IF Brommapojkarna": "브롬마포이카르나",
  "IF Elfsborg": "엘프스보리",
  "IFK Goteborg": "IFK 예테보리",
  "IFK Göteborg": "IFK 예테보리",
  "Kalmar FF": "칼마르",
  "Malmo FF": "말뫼",
  "Mjallby AIF": "엘라비 AIF",
  "Mjällby": "엘라비 AIF",
  "Orgryte IS": "오르그뤼테",
  "Sirius": "시리우스",
  "Vasteras SK FK": "베스테로스",

  // ===== 🇵🇱 에크스트라클라사 (Ekstraklasa) =====
  "Arka Gdynia": "아르카 그디니아",
  "Cracovia Krakow": "크라코비아",
  "GKS Katowice": "GKS 카토비체",
  "Gornik Zabrze": "고르니크 자브제",
  "Górnik Zabrze": "고르니크 자브제",
  "Jagiellonia": "야기엘로니아",
  "Jagiellonia Białystok": "야기엘로니아 비아위스토크",
  "Korona Kielce": "코로나 키엘체",
  "Lech Poznan": "레흐 포즈난",
  "Lech Poznań": "레흐 포즈난",
  "Lechia Gdansk": "레히아 그단스크",
  "Legia Warszawa": "레기아 바르샤바",
  "Motor Lublin": "모토르 루블린",
  "Nieciecza": "부르크베트 테르말리차",
  "Piast Gliwice": "피아스트 글리비체",
  "Pogon Szczecin": "포곤 슈체친",
  "Radomiak Radom": "라도미아크 라돔",
  "Raków Częstochowa": "라쿠프 첸스토호바",
  "Widzew Łódź": "비드제브 로즈",
  "Wisla Plock": "비스와 프워츠크",
  "Zaglebie Lubin": "자글레비에 루빈",

  // Finland (핀란드)
"AC Oulu": "AC 오울루",
"FF Jaro": "FF 야로",
"HIFK Helsinki": "HIFK 헬싱키",
"HJK": "HJK 헬싱키",
"HJK Helsinki": "HJK 헬싱키",
"HJK W": "HJK 헬싱키",
"FC Inter Turku": "인터 투르쿠", // ⚠️ "Inter Turku"와 같은 팀인데 한글 표기가 달라서(FC 접두 유무) matchTeam()이 다른 팀으로 오판하던 것 통일함(2026-08 감사)
"Inter Turku": "인터 투르쿠",
"Inter Turku II": "인터 투르쿠 II",
"Ilves": "일베스",
"Ilves II": "일베스 II",
"Ilves W": "일베스",
"Haka": "하카",
"KuPS": "쿠오피온 팔로세우라",
"KuPS Akatemia": "쿠오피온 팔로세우라 아카데미",
"KuPS W": "쿠오피온 팔로세우라",
"SJK": "SJK 세이나요엔",
"SJK Akatemia": "SJK 아카데미",
"SJK-juniorit": "SJK 주니오리트",
"VPS": "VPS",
"Gnistan": "IF 그니스탄",
"Lahti": "라티",
"Turku PS": "투르쿠 PS",
"PuiU Helsinki": "푸이우 헬싱키",
"Jaro 2": "야로 II",
"Mariehamn": "마리에함",

// Morocco (모로코)
"Renaissance Berkane": "RS 베르카네",
"Olympique Safi": "올림피크 데 사피",
"Ittihad Tanger": "IR 탕헤르",
"Olympique Dcheïra": "올림피크 드체이라",
"Wydad AC": "위다드 AC",
"Yacoub El Mansour": "야쿠브 엘 만수르",
"FAR Rabat": "FAR 라바트",
"FUS Rabat": "FUS 라바트",
"Fath Casablanca": "파스 카사블랑카",
"Hassania Agadir": "하사니아 아가디르",
"Kawkab Marrakech": "카우카브 마라케시",
"MAS Fes": "마그레브 드 페스",
"Maghreb Fès": "마브레브 페즈",
"Difaa EL Jadida": "디파 엘 자디다",
"Moghreb Tetouan": "모그레브 테투안",
"Racing de Casablanca": "라싱 카사블랑카",
"Raja Casablanca": "라자 카사블랑카",
"CODM Meknès": "COD 메크네스",
"UTS Rabat": "UTS 라바트",
"Wydad Casablanca": "위다드 카사블랑카",
"CR Khemis Zemamra": "RCA 제맘라",

  // ===== 🇯🇵 J1리그 (J1 League) =====
  "Avispa Fukuoka": "아비스파 후쿠오카",
  "Cerezo Osaka": "세레소 오사카",
  "FC Tokyo": "FC 도쿄",
  "Fagiano Okayama": "파지아노 오카야마",
  "Gamba Osaka": "감바 오사카",
  "JEF United Chiba": "JEF 유나이티드 지바",
  "Kashima": "가시마 앤틀러스",
  "Kashiwa Reysol": "가시와 레이솔",
  "Kawasaki Frontale": "가와사키 프론탈레",
  "Kawasaki": "가와사키 프론탈레",
  "Kyoto Sanga": "교토 상가",
  "Kyoto Sanga FC": "교토 상가",
  "Machida Zelvia": "마치다 젤비아",
  "Mito Hollyhock": "미토 홀리혹",
  "Nagoya Grampus": "나고야 그램퍼스",
  "Sanfrecce Hiroshima": "산프레체 히로시마",
  "Sanfrecce": "산프레체 히로시마",
  "Shimizu S-pulse": "시미즈 S펄스",
  "Tokyo Verdy": "도쿄 베르디",
  "Urawa": "우라와 레드 다이아몬즈",
  "Urawa Red Diamonds": "우라와 레드 다이아몬즈",
  "V-varen Nagasaki": "V파렌 나가사키",
  "Vissel Kobe": "비셀 고베",
  "Yokohama F. Marinos": "요코하마 F마리노스",

  // ===== 🇰🇷 K리그 (K League) =====
  "Bucheon FC 1995": "부천 FC",
  "Daejeon Citizen": "대전 시티즌",
  "Daejeon Hana Citizen": "대전 시티즌",
  "FC Anyang": "FC 안양",
  "FC Seoul": "FC 서울",
  "Gangwon FC": "강원 FC",
  "Gimcheon Sangmu FC": "김천 상무 FC",
  "Gimcheon Sangmu": "김천 상무 FC",
  "Gwangju FC": "광주 FC",
  "Incheon United": "인천 유나이티드",
  "Jeju United FC": "제주 유나이티드",
  "Jeju SK": "제주 유나이티드",
  "Jeonbuk Motors": "전북 현대",
  "Jeonbuk Hyundai Motors FC": "전북 현대",
  "Pohang Steelers": "포항 스틸러스",
  "Ulsan Hyundai FC": "울산 HD FC",
  "Ulsan HD FC": "울산 HD FC",
  "Ansan Greeners": "안산 그리너스",
  "Asan Mugunghwa": "아산 무궁화",
  "Chungnam Asan FC": "아산 무궁화",
  "Busan I Park": "부산 아이파크",
  "Busan I'Park": "부산 아이파크",
  "Cheonan City": "천안 시티",
  "Cheongju": "청주 FC",
  "Daegu FC": "대구 FC",
  "Gimhae City": "김해 시티",
  "Gimhae FC 2008": "김해 시티",
  "Gimpo Citizen": "김포 시티즌",
  "Gimpo FC": "김포 시티즌",
  "Gyeongnam FC": "경남 FC",
  "Hwaseong": "화성 FC",
  "Hwaseong FC": "화성 FC",
  "Jeonnam Dragons": "전남 드래곤즈",
  "Paju Citizen": "파주 시티즌",
  "Paju Frontier": "파주 시티즌",
  "Seongnam FC": "성남 FC",
  "Seoul E-Land FC": "서울 이랜드 FC",
  "Suwon Bluewings": "수원 삼성 블루윙즈",
  "Suwon Samsung Bluewings": "수원 삼성 블루윙즈",
  "Suwon City FC": "수원 FC",
  "Suwon FC": "수원 FC",
  "Suwon FMC W": "수원 FC",
  "Gumi Sportstoto W": "세종스포츠토토",
  "Incheon Red Angels W": "현대제철 레드엔젤스",
  "Yongin City": "용인 FC",
  "Yongin FC": "용인 FC",
  "Jeonbuk Motors II": "전북 현대모터스 II",

// ===== 🇰🇷 한국 FA컵 시민구단/아마추어팀 추가분 =====
  "Anseong": "안성",
  "Areum": "아름", // 추정 - 확인 필요
  "Busan Transportation": "부산교통공사",
  "Busan Transport Corp": "부산교통공사",
  "Cheongju Showking": "청주 쇼킹", // 추정 - 확인 필요
  "Chuncheon": "춘천",
  "Dangjin Citizen": "당진시민",
  "Gangneung City": "강릉시청",
  "Geoje Citizen": "거제시민",
  "Gijang United": "기장 유나이티드",
  "Gyeongju HNP": "경주 한수원",
  "Haman": "함안",
  "Jecheon Citizen": "제천시민",
  "Jincheon": "진천",
  "Jinju Citizen": "진주시민",
  "Jungnang Chorus Mustang": "중랑 코러스 무스탕", // 추정 - 확인 필요
  "Mokpo City": "목포시청",
  "Namyangju": "남양주",
  "Pyeongchang United": "평창 유나이티드",
  "Pyeongtaek Citizen": "평택시민",
  "Sejong SA": "세종 SA", // 추정 - 확인 필요
  "Seogot": "서곶", // 추정 - 확인 필요
  "Seosan Pioneer": "서산 파이오니어",
  "Siheung Citizen": "시흥시민",
  "Ulsan Citizen": "울산시민",
  "Ulsan FC": "울산 FC",
  "Yangcheon TNT": "양천 TNT",
  "Yangpyeong": "양평",
  "Yangsan United": "양산 유나이티드",
  "Yeoju Sejong": "여주 세종",
  "Yeoju FC": "여주 세종",
  "Yeonsu Songdo": "연수 송도",
  "Changwon City": "창원시청",
  "Geumsan Insam": "금산 인삼",
  "Pocheon": "포천 시민",
  "Daejeon Korail": "대전 코레일",
  "Yeoncheon FC": "연천 FC",

  // ===== 🇺🇸 MLS =====
  "Atlanta United FC": "애틀랜타 유나이티드",
  "Atlanta United": "애틀랜타 유나이티드",
  "Austin": "오스틴 FC",
  "Austin FC": "오스틴 FC",
  "CF Montreal": "CF 몽레알",
  "Montreal": "CF 몽레알",
  "Charlotte": "샬럿 FC",
  "Charlotte FC": "샬럿 FC",
  "Chicago Fire": "시카고 파이어",
  "Chicago": "시카고",
  "Colorado Rapids": "콜로라도 래피즈",
  "Colorado": "콜로라도",
  "Columbus Crew": "콜럼버스 크루",
  "Columbus": "콜럼버스 크루",
  "DC United": "DC 유나이티드",
  "FC Cincinnati": "FC 신시내티",
  "Cincinnati": "FC 신시내티",
  "FC Dallas": "FC 댈러스",
  "Dallas": "FC 댈러스",
  "Houston Dynamo": "휴스턴 다이나모",
  "Houston": "휴스턴",
  "Inter Miami": "인터 마이애미",
  "Inter Miami CF": "인터 마이애미",
  "Los Angeles FC": "LA FC",
  "LAFC": "LA FC",
  "Los Angeles Galaxy": "LA 갤럭시",
  "LA Galaxy": "LA 갤럭시",
  "Minnesota United FC": "미네소타 유나이티드",
  "Minnesota": "미네소타",
  "Nashville SC": "내슈빌 SC",
  "New England Revolution": "뉴잉글랜드 레볼루션",
  "New England": "뉴잉글랜드 레볼루션",
  "New York City FC": "뉴욕 시티 FC",
  "NYCFC": "뉴욕 시티 FC",
  "New York Red Bulls": "뉴욕 레드불스",
  "Red Bull New York": "뉴욕 레드불스",
  "NY Red Bulls": "뉴욕 레드불스",
  "Orlando City SC": "올랜도 시티",
  "Orlando": "올랜도 시티",
  "Orlando City": "올랜도 시티",
  "Temperley": "템페를레이",
  "Philadelphia Union": "필라델피아 유니온",
  "Philadelphia": "필라델피아",
  "Portland Timbers": "포틀랜드 팀버스",
  "Portland": "포틀랜드",
  "Real Salt Lake": "레알 솔트레이크",
  "Salt Lake": "솔트레이크",
  "San Diego": "샌디에이고 FC",
  "San Diego FC": "샌디에이고 FC",
  "San Jose Earthquakes": "산호세 어스퀘이크스",
  "San Jose": "산호세",
  "Seattle Sounders": "시애틀 사운더스",
  "Sporting Kansas City": "스포르팅 캔자스시티",
  "Sporting KC": "스포르팅 캔자스시티", // fotmob/ESPN 등이 축약 표기를 쓰는 경우 대비(2군 "Sporting KC II"와는
  // 다른 팀이라 matchTeam()의 부분일치 폴백 제거 이후 이 동의어 등록 없이는 매칭이 안 됨, 2026-08 확인)
  "St. Louis City": "세인트루이스 시티",
  "Toronto FC": "토론토 FC",
  "Toronto": "토론토 FC",
  "Vancouver Whitecaps": "밴쿠버 화이트캡스",

  // ===== 🇦🇺 A리그 (A-League) =====
  "Adelaide United": "애들레이드 유나이티드",
  "Auckland": "오클랜드 FC",
  "Brisbane Roar": "브리즈번 로어",
  "Central Coast Mariners": "센트럴 코스트 매리너스",
  "Macarthur": "매카서 FC",
  "Melbourne City": "멜버른 시티",
  "Melbourne Victory": "멜버른 빅토리",
  "Newcastle Jets": "뉴캐슬 제츠",
  "Perth Glory": "퍼스 글로리",
  "Sydney": "시드니 FC",
  "Wellington Phoenix": "웰링턴 피닉스",
  "Western Sydney Wanderers": "웨스턴 시드니 원더러스",

  // ===== ⚾ KBO =====
  "Doosan Bears": "두산 베어스",
  "Hanwha Eagles": "한화 이글스",
  "KIA Tigers": "KIA 타이거즈",
  "KT Wiz Suwon": "KT 위즈",
  "Kiwoom Heroes": "키움 히어로즈",
  "LG Twins": "LG 트윈스",
  "Lotte Giants": "롯데 자이언츠",
  "NC Dinos": "NC 다이노스",
  "SSG Landers": "SSG 랜더스",
  "Samsung Lions": "삼성 라이온스",

  // ===== ⚾ MLB =====
  "Arizona Diamondbacks": "애리조나 다이아몬드백스",
  "Diamondbacks": "애리조나 다이아몬드백스",
  "Athletics": "애슬레틱스",
  "Atlanta Braves": "애틀랜타 브레이브스",
  "Baltimore Orioles": "볼티모어 오리올스",
  "Boston Red Sox": "보스턴 레드삭스",
  "Chicago Cubs": "시카고 컵스",
  "Chicago White Sox": "시카고 화이트삭스",
  "Cincinnati Reds": "신시내티 레즈",
  "Cleveland Guardians": "클리블랜드 가디언스",
  "Colorado Rockies": "콜로라도 로키스",
  "Detroit Tigers": "디트로이트 타이거즈",
  "Houston Astros": "휴스턴 애스트로스",
  "Kansas City Royals": "캔자스시티 로열스",
  "Los Angeles Angels": "LA 에인절스",
  "Los Angeles Dodgers": "LA 다저스",
  "Miami Marlins": "마이애미 말린스",
  "Milwaukee Brewers": "밀워키 브루어스",
  "Minnesota Twins": "미네소타 트윈스",
  "New York Mets": "뉴욕 메츠",
  "New York Yankees": "뉴욕 양키즈",
  "Philadelphia Phillies": "필라델피아 필리스",
  "Pittsburgh Pirates": "피츠버그 파이러츠",
  "San Diego Padres": "샌디에이고 파드리스",
  "San Francisco Giants": "샌프란시스코 자이언츠",
  "Seattle Mariners": "시애틀 매리너스",
  "St.Louis Cardinals": "세인트루이스 카디널스",
  "Tampa Bay Rays": "탬파베이 레이스",
  "Texas Rangers": "텍사스 레인저스",
  "Toronto Blue Jays": "토론토 블루제이즈",
  "Washington Nationals": "워싱턴 내셔널스",

  // ===== ⚾ NPB =====
  "Chiba Lotte Marines": "지바 롯데 마린스",
  "Chunichi Dragons": "주니치 드래곤스",
  "Fukuoka S. Hawks": "소프트뱅크 호크스",
  "Hanshin Tigers": "한신 타이거스",
  "Hiroshima Carp": "히로시마 도요 카프",
  "Nippon Ham Fighters": "니혼햄 파이터즈",
  "Orix Buffaloes": "오릭스 버팔로스",
  "Rakuten Gold. Eagles": "라쿠텐 골든이글스",
  "Seibu Lions": "세이부 라이온즈",
  "Yakult Swallows": "야쿠르트 스왈로우스",
  "Yokohama BayStars": "요코하마 DeNA 베이스타스",
  "Yomiuri Giants": "요미우리 자이언츠",

  // ===== ⚾ CPBL (대만) =====
  "Chinatrust Brothers": "중신 브라더스",
  "Fubon Guardians": "푸방 가디언즈",
  "Rakuten Monkeys": "라쿠텐 몽키스",
  "TSG Hawks": "TSG 호크스",
  "Uni Lions": "유니 라이온즈",
  "Wei Chuan Dragons": "웨이촨 드래곤스",

  // ===== 🏀 NBA =====
  "Atlanta Hawks": "애틀랜타 호크스",
  "Boston Celtics": "보스턴 셀틱스",
  "Cleveland Cavaliers": "클리블랜드 캐벌리어스",
  "Denver Nuggets": "덴버 너기츠",
  "Detroit Pistons": "디트로이트 피스톤스",
  "Houston Rockets": "휴스턴 로키츠",
  "Los Angeles Lakers": "LA 레이커스",
  "Minnesota Timberwolves": "미네소타 팀버울브스",
  "New York Knicks": "뉴욕 닉스",
  "Oklahoma City Thunder": "오클라호마시티 썬더",
  "Orlando Magic": "올랜도 매직",
  "Philadelphia 76ers": "필라델피아 76ers",
  "Phoenix Suns": "피닉스 선즈",
  "Portland Trail Blazers": "포틀랜드 트레일블레이저스",
  "San Antonio Spurs": "샌안토니오 스퍼스",
  "Toronto Raptors": "토론토 랩터스",
  "Utah Jazz": "유타 재즈",
  "Sacramento Kings": "새크라멘토 킹스",
  "Brooklyn Nets": "브루클린 네츠",
  "Memphis Grizzlies": "멤피스 그리즐리",
  "Chicago Bulls": "시카고 불스",
  "Dallas Mavericks": "댈러스 매버릭스",
  "Golden State Warriors": "골든스테이트 워리어스",
  "LA Clippers": "LA 클리퍼스",
  "Miami Heat": "마이애미 히트",
  "Milwaukee Bucks": "밀워키 벅스",
  "Charlotte Hornets": "샬럿 호네츠",
  "Indiana Pacers": "인디애나 페이서스",
  "New Orleans Pelicans": "뉴올리언스 펠리컨스",
  "Washington Wizards": "워싱턴 위저즈",
  "Los Angeles Clippers": "LA 클리퍼스",

  // ===== 🏀 KBL =====
  "Anyang JungKwanJang": "안양 정관장",
  "Goyang Sono": "고양 소노",
  "KCC Egis": "KCC 이지스",
  "LG Sakers": "LG 세이커스",  
  "Daegu KOGAS": "한국가스공사",
  "SK Knights": "SK",
  "Samsung Thunders": "삼성",
  "Changwon LG": "LG",
  "Ulsan Hyundai Mobis": "현대모비스",
  "Hyundai Mobis": "현대모비스",
  "Suwon KT": "KT",
  "KT Sonicboom": "KT",
  "Suwon KT Sonicboom": "KT",
  "Wonju DB": "DB",
  "DB Promy": "DB",

  // ===== 🏀 WKBL =====
  "Samsung Blue Minx": "삼성생명",      
  "KB Stars": "KB스타즈",               
  "Shinhan Bank S-Birds": "신한은행",   
  "Woori Bank WON": "우리은행",         
  "Hana Bank": "하나은행",              
  "BNK Sum": "부산 BNK 썸",             

  // ===== 🏐 V-리그 남자부 (KOVO) =====
  "Korean Air Jumbos": "대한항공",
  "Samsung Fire Bluefangs": "삼성화재",
  "KB Insurance Stars": "KB손해보험",
  "Hyundai Capital Skywalkers": "현대캐피탈",
  "KEPCO Vixtorm": "한국전력",
  "OK Savings Bank OKman": "OK저축은행",
  "Woori Card WON": "우리카드",

  // ===== 🏐 V-리그 여자부 (WKOVO) =====
  "Hyundai E&C Hillstate": "현대건설",
  "Korea Expressway Hi-pass": "한국도로공사",
 "Jungkwanjang Red Sparks": "정관장",
  "Heungkuk Life Pink Spiders": "흥국생명",
  "GS Caltex Seoul KIXX": "GS칼텍스",
  "IBK Altos": "IBK기업은행",
  "SOOP Supers": "페퍼저축은행",

  // ===== 🏒 NHL =====
  "Anaheim Ducks": "애너하임 덕스",
  "Boston Bruins": "보스턴 브루인스",
  "Buffalo Sabres": "버펄로 세이버스",
  "Carolina Hurricanes": "캐롤라이나 허리케인스",
  "Colorado Avalanche": "콜로라도 애벌랜치",
  "Dallas Stars": "댈러스 스타스",
  "Edmonton Oilers": "에드먼턴 오일러스",
  "Los Angeles Kings": "LA 킹스",
  "Montreal Canadiens": "몬트리올 캐네이디언스",
  "Ottawa Senators": "오타와 세너터스",
  "Philadelphia Flyers": "필라델피아 플라이어스",
  "Pittsburgh Penguins": "피츠버그 펭귄스",
  "Tampa Bay Lightning": "탬파베이 라이트닝",
  "Utah Mammoth": "유타 매머스",
  "Vegas Golden Knights": "베가스 골든나이츠",

  // ===== 🎮 LOL (LCK) =====
  "BNK FEARX": "BNK 피어엑스",
  "BNK FearX Youth": "BNK 피어엑스 유스",
  "DN SOOPers": "DN 수퍼스",
  "DN SOOPers Challengers": "DN 수퍼스 챌린저스",
  "Dplus KIA": "디플러스 기아",
  "Dplus KIA Challengers": "디플러스 기아 챌린저스",
  "Gen.G": "젠지",
  "Gen.G Esports": "젠지",
  "Gen.G Global Academy": "젠지 글로벌 아카데미",
  "HANJIN BRION": "한진 브리온",
  "HANJIN BRION Challengers": "한진 브리온 챌린저스",
  "Hanwha Life Esports": "한화생명 e스포츠",
  "Hanwha Life Esports Challengers": "한화생명 e스포츠 챌린저스",
  "KT Rolster": "KT 롤스터",
  "KT Rolster Challengers": "KT 롤스터 챌린저스",
  "Kiwoom DRX": "키움 DRX",
  "Kiwoom DRX Academy": "키움 DRX 아카데미",
  "Kiwoom DRX Challengers": "키움 DRX 챌린저스",
  "Nongshim Esports Academy": "농심 레드포스 아카데미",
  "Nongshim Red Force": "농심 레드포스",
  "T1 Academy": "T1 아카데미",

  // ===== 🎮 LOL (LPL) =====
  "Bilibili Gaming": "빌리빌리 게이밍",
  "Bilibili Gaming Junior": "빌리빌리 게이밍 주니어",
  "EDward Gaming": "에드워드 게이밍",
  "EDward Gaming Youth Team": "에드워드 게이밍 유스",
  "FunPlus Phoenix": "펀플러스 피닉스",
  "Invictus Gaming": "인빅투스 게이밍",
  "JD Gaming": "JD 게이밍",
  "LGD Gaming": "LGD 게이밍",
  "LNG Esports": "LNG 이스포츠",
  "Lynn Vision": "린 비전",
  "Nova Esports": "노바 이스포츠",
  "Oh My God": "오 마이 갓",
  "Rare Atom": "레어 아톰",
  "T1": "T1",
  "ThunderTalk Gaming": "썬더토크 게이밍",
  "Top Esports": "탑 이스포츠",
  "Ultra Prime": "울트라 프라임",
  "Weibo Gaming": "웨이보 게이밍",
  "Weibo Gaming Youth Team": "웨이보 게이밍 유스",

  // ===== 🎮 LOL (LEC/LCS/국제) =====
  "Cloud9": "클라우드9",
  "Dignitas": "디그니타스",
  "Evil Geniuses": "이블 지니어스",
  "FlyQuest": "플라이퀘스트",
  "Fnatic": "프나틱",
  "G2 Esports": "G2 이스포츠",
  "GIANTX": "자이언트엑스",
  "Karmine Corp": "카르민 코프",
  "LYON": "리옹",
  "M80": "M80",
  "Movistar KOI": "모비스타 KOI",
  "NRG Esports": "NRG 이스포츠",
  "Ninjas in Pyjamas": "닌자스 인 파자마스",
  "Rogue": "로그",
  "SK Gaming": "SK 게이밍",
  "Sentinels": "센티넬스",
  "Shopify Rebellion": "쇼피파이 리벨리온",
  "Team Heretics": "팀 헤레틱스",
  "Team Liquid": "팀 리퀴드",
  "Team Vitality": "팀 바이탈리티",
  "Team WE": "팀 WE",
  "Virtus.pro": "버투스 프로",

  // ===== 🎮 LOL - EWC/LEC/LCS 추가팀 =====
  "Detonation FocusMe": "데토네이션 포커스미",
  "DetonatioN FocusMe": "데토네이션 포커스미",
  "DetonatioN FocusMe Academy": "데토네이션 포커스미 아카데미",
  "GAM Esports": "GAM 이스포츠",
  "Team Liquid Brazil": "팀 리퀴드 브라질",
  "LOUD": "라우드",
  "Isurus": "이수루스",
  "Leviatan Esports": "레비아탄 이스포츠",
  "Leviatán Esports": "레비아탄 이스포츠",
  "RED Canids": "레드 카니즈",
  "paiN Gaming": "페인 게이밍",
  "FURIA Esports": "푸리아 이스포츠",
  "Vivo Keyd Stars": "비보 케이드 스타즈",
  "Natus Vincere": "나투스 빈체레",
  "Vitality.Bee": "비탈리티 비",
  "Shifters": "시프터스",
  "Team Heretics Academy": "팀 헤레틱스 아카데미",
  "GIANTX GC": "자이언트엑스 GC",
  "Karmine Corp Blue": "카르민 코프 블루",
  "Nemiga Gaming": "네미가 게이밍",
  "CTBC Flying Oyster": "CTBC 플라잉 오이스터",
  "CTBC Flying Oyster Academy": "CTBC 플라잉 오이스터 아카데미",
  "Disguised": "디스가이즈드",
  "FlyQuest RED": "플라이퀘스트 레드",
  "NRG": "NRG",
  "G2 Gozen": "G2 고젠",
  "Team Falcons": "팀 팔콘스",
  "Fukuoka SoftBank Hawks Gaming": "후쿠오카 소프트뱅크 호크스 게이밍",
  "Estral Esports": "에스트랄 이스포츠",
  "Zeta Games": "제타 게임즈",
  "ZETA DIVISION": "제타 디비전",
  "Wolves Esports": "울브스 이스포츠",
  "Anyone's Legend": "애니원즈 레전드",
  "Solary": "솔라리",

  // ===== 🏒 하키 추가팀 =====
  "Avangard Omsk": "아방가르드 옴스크",
  "Bars Kazan": "바르스 카잔",
  "Lokomotiv Yaroslavl": "로코모티프 야로슬라블",
  "Magnitogorsk": "마그니토고르스크",
  "Minnesota Wild": "미네소타 와일드",

  //캐나다 축구팀
  "Atlético Ottawa": "아틀레티코 오타와",
  "Vancouver FC": "밴쿠버 FC", // ⚠️ "Vancouver"와 같은 CPL 클럽인데 한글 표기가 달라서 통일함(MLS "Vancouver Whitecaps"와는 다른 팀, 혼동 주의, 2026-08 감사)
  "Vancouver": "밴쿠버 FC",
  "Pacific FC": "퍼시픽 FC",
  "Forge FC": "포지 FC",
  "Inter Toronto FC": "요크 유니티드 FC",

  // 국가대표팀
  "Canada": "캐나다",
  "Finland": "핀란드",
  "Finland W": "핀란드",
  "Sweden": "스웨덴",
  "Sweden W": "스웨덴",
  "Tunisia": "튀니지",
  "Czech Republic": "체코",
  "Czechia": "체코",
  "Czechia W": "체코",
  "Bosnia-Herzegovina": "보스니아 헤르체고비나",
  "Paraguay": "파라과이",
  "Russia": "러시아",
  "USA": "미국",
  "United States": "미국",
  "Qatar": "카타르",
  "Morocco": "모로코",
  "Curacao": "퀴라소",
  "Switzerland": "스위스",
  "Denmark": "덴마크",
  "Norway": "노르웨이",
  "Slovakia": "슬로바키아",
  "Slovakia W": "슬로바키아",
  "Latvia": "라트비아",
  "Latvia W": "라트비아",
  "Slovenia": "슬로베니아",
  "Austria": "오스트리아",
  "Austria W": "오스트리아",
  "Hungary": "헝가리",
  "Great Britain": "영국",
  "Lithuania W": "리투아니아",
  "Lithuania": "리투아니아",

  // ===== 🏀 농구 추가팀 =====
  // B리그 (일본)
  "Akita": "아키타 노던해피네츠",
  "Altiri Chiba": "알티리 지바",
  "Alvark": "알박 도쿄",
  "Brave Thunders": "가와사키 브레이브 선더스",
  "Chiba": "지바 제츠",
  "Diamond Dolphins": "나고야 다이아몬드 돌핀스",
  "Gunma": "군마 크레인 선더스",
  "Hiroshima D.": "히로시마 드래곤 플라이스",
  "Hokkaido": "레바ンガ 홋카이도",
  "Ibaraki Robots": "이바라키 로봇스",
  "Koshigaya Alphas": "코시가야 알파스",
  "Kyoto": "교토 하나나루",
  "Nagasaki": "나가사키 벨로세아",
  "Nagoya Fighting Eagles": "나고야 파이팅 이글스",
  "NeoPhoenix": "산엔 네오피닉스",
  "Osaka": "오사카 에베사",
  "Ryukyu": "류큐 골든킹스",
  "Saga": "사가 발루인스",
  "SeaHorses Mikawa": "시호스 미카와",
  "Sendai": "센다이 89ers",
  "Shiga": "시가 레이크스타즈",
  "Shimane": "시마네 스사노오 매직",
  "Sun Rockers Shibuya": "선로커스 시부야",
  "Toyama": "도야마 그라우지스",
  "Utsunomiya Brex": "우쓰노미야 브렉스",
  "Yokohama": "요코하마 비콜",
  // CBA (중국)
  "Beijing": "베이징 오리올스",
  "Beijing Royal Fighters": "베이징 로열 파이터스",
  "Fujian": "푸젠 스터금",
  "Guangdong": "광둥 서던 타이거스",
  "Guangzhou": "광저우 루이안",
  "Jiangsu Dragons": "장쑤 드래곤스",
  "Jilin": "지린 노스이스트 타이거스",
  "Liaoning": "랴오닝 플라잉 레오파즈",
  "Nanjing Tongxi": "난징 통시 몽키 킹스",
  "Ningbo Rockets": "닝보 로켓츠",
  "Qingdao": "칭다오 이글스",
  "Shandong": "산둥 하이쥔스",
  "Shanghai": "상하이 샤크스",
  "Shanxi Zhongyu": "산시 중위",
  "Shenzhen": "선전 아비에이터스",
  "Sichuan": "쓰촨 블루웨일스",
  "Tianjin": "톈진 골든라이온스",
  "Xinjiang": "신장 플라잉 타이거스",
  "Zhejiang Chouzhou": "저장 저우저우 차이나 라이온스",
  "Zhejiang Guangsha": "저장 광샤 라이온스",

  // 유로리그
  "Fenerbahce": "페네르바흐체",

  "Zalgiris Kaunas": "잘기리스 카우나스",
  "Olimpiacos": "올림피아코스",
  "Panathinaikos": "파나티나이코스",
  "Hapoel Tel Aviv": "하포엘 텔아비브",
  "Olympiacos": "올림피아코스",
  "Iberia 1999": "사부르탈로",
  "PAOK Thessaloniki": "PAOK",

  //네덜란드
  "Telstar": "텔스타",
  "ADO Den Haag": "ADO 덴하흐",

  //웨일스
  "Barry Town": "배리 타운",
  "Cambrian & Clydach": "캠브리언 & 클리다치",
  "Cambrian United": "캠브리언 & 클리다치",
  "Ammanford AFC": "아만포드", // ⚠️ "Ammanford"와 같은 팀인데 한글 표기가 달라서 통일함(2026-08 감사)
  "Colwyn Bay": "콜윈베이 FC",
  "Llandudno": "란디드노",
  "Llandudno FC": "란디드노", // ⚠️ "Llandudno"와 같은 팀인데 한글 표기가 달라서 통일함(2026-08 감사)
  "Llaneros": "야네로스",
  "Llaneros FC": "야네로스",
  "Airbus UK Broughton": "에어버스 UK 브로튼",
  "Ammanford": "아만포드",
  "Cardiff Met University": "카디프 메트",
  "Flint Town United": "플린트 타운",
  "Connah's Quay Nomads": "코나스 퀘이",
  "Haverfordwest": "하버포드웨스트",

  // WNBA
  "Atlanta Dream W": "애틀랜타 드림",
  "Chicago Sky W": "시카고 스카이",
  "Connecticut Sun W": "코네티컷 선",
  "Dallas Wings W": "댈러스 윙스",
  "Golden State Valkyries W": "골든스테이트 발키리스",
  "Indiana Fever W": "인디애나 피버",
  "Las Vegas Aces W": "라스베이거스 에이시스",
  "Los Angeles Sparks W": "LA 스파크스",
  "Minnesota Lynx W": "미네소타 링크스",
  "New York Liberty W": "뉴욕 리버티",
  "Phoenix Mercury W": "피닉스 머큐리",
  "Portland Fire W": "포틀랜드 파이어",
  "Seattle Storm W": "시애틀 스톰",
  "Washington Mystics W": "워싱턴 미스틱스",
  "Toronto Tempo W": "토론토 템포",
  // 아시아 챔피언스리그
  "Xac Broncos": "Xac 브롱코스",
  "New Taipei Kings": "뉴 타이베이 킹스",
  "Taoyuan Pauian Pilots": "타오위안 포이안 파일럿츠",
  "Johor Southern Tigers": "조호르 서던 타이거스",
  "Dewa United": "데와 유나이티드",
  "Hi-Tech": "하이테크",

  // ===== ⚽ 축구 추가 (실제 분석 대상 리그) =====
  // 2. 분데스리가
  "1. FC Kaiserslautern": "카이저슬라우테른",
  "Kaiserslautern": "카이저슬라우테른",
  "1. FC Magdeburg": "마그데부르크",
  "Magdeburg": "마그데부르크",
  "1. FC Nürnberg": "뉘른베르크",
  "Arminia Bielefeld": "아르미니아 빌레펠트",
  "Dynamo Dresden": "디나모 드레스덴",
  "Eintracht Braunschweig": "아인트라흐트 브라운슈바이크",
  "Fortuna Düsseldorf": "포르투나 뒤셀도르프",
  "Hannover 96": "하노버 96",
  "Hertha BSC": "헤르타 베를린",
  "Holstein Kiel": "홀슈타인 킬",
  "Karlsruher SC": "카를스루허",
  "Preußen Münster": "프로이센 뮌스터",
  "Rot-Weiß Essen": "로트바이스 에센",
  "SV Darmstadt 98": "다름슈타트 98",
  "Darmstadt": "다름슈타트 98",
  "SpVgg Greuther Fürth": "그로이터 퓌르트",
  "Greuther Fürth": "그로이터 퓌르트",
  "VfL Bochum": "보훔",
  "Bochum": "보훔",

  // 세리에B (이탈리아)
  "Bari": "바리",
  "Catanzaro": "카탄자로",
  "Cesena": "체세나",
  "Empoli": "엠폴리",
  "Juve Stabia": "유베 스타비아",
  "Mantova": "만토바",
  "Modena": "모데나",
  "Padova": "파도바",
  "Palermo": "팔레르모",
  "Pescara": "페스카라",
  "Pisa": "피사",
  "Reggiana": "레자나",
  "Sampdoria": "삼프도리아",
  "Spezia": "스페치아",
  "Sudtirol": "수드티롤",
  "Virtus Entella": "비르투스 엔텔라",
  "Avellino": "아벨리노",
  "Ascoli": "아스콜리 피키오",

  // 리그2 (프랑스)
  "Amiens": "아미앵",
  "Annecy": "안시",
  "pau": "PAU",
  "Bastia": "바스티아",
  "Boulogne": "불로뉴",
  "Clermont Foot": "클레르몽",
  "Dunkerque": "됭케르크",
  "Guingamp": "갱강",
  "Laval": "라발",
  "Montpellier": "몽펠리에",
  "Nancy": "낭시",
  "RED Star FC 93": "레드 스타",
  "RED Star": "레드 스타",
  "Reims": "랭스",
  "Rodez": "로데스",
  "Rouen": "루앙",
  "Grenoble": "그르노블",

  // 세군다 디비시온 (스페인)
  "Albacete": "알바세테",
  "Almeria": "알메리아",
  "Burgos": "부르고스",
  "Cadiz": "카디스",
  "Castellón": "카스테욘",
  "Cultural Leonesa": "쿨투랄 레오네사",
  "Eibar": "에이바르",
  "FC Andorra": "FC 안도라",
  "Granada CF": "그라나다",
  "Huesca": "우에스카",
  "Las Palmas": "라스팔마스",
  "Leganes": "레가네스",
  "Linares Unido": "리나레스",
  "Mirandes": "미란데스",
  "Oviedo": "오비에도",
  "Real Sociedad II": "레알 소시에다드 B",
  "Real Valladolid": "바야돌리드",
  "Valladolid": "바야돌리드",
  "Zaragoza": "사라고사",

  // 세리에A (브라질) 추가
  "Athletico Paranaense": "아틀레치쿠 파라나엔시",
  "Bahia": "바이아",
  "Chapecoense-sc": "샤페코엔스",
  "Chapecoense AF": "샤페코엔스",
  "Coritiba": "코리치바",
  "Cruzeiro": "크루제이루",
  "Mirassol": "미라솔",
  "Red Bull Bragantino": "RB 브라간치누",
  "Santos": "산투스",
  "Santos FC": "산투스",
  "Sao Paulo": "상파울루",
  "Vitoria": "비토리아",
  "Independiente Petrolero": "인데펜디엔테 페트롤레로",
  "Club Deportivo Los Chankas": "CD 로스 찬카스",
  "Deportivo Cuenca": "데포르티보 쿠엔카",
  "Fortaleza EC": "포르탈레자 EC",
  "Barracas Central": "바라카스 센트랄",
  "Puerto Cabello": "푸에르토 카베요",
  "Cienciano": "시엔시아노",
  "Remo": "헤무",

  // K리그 WK리그
  "Boeun Sangmu W": "문경 상무",
  "Changnyeong W": "창녕 FC",
  "Gumi Sportstoto": "세종스포츠토토",
  "Gyeongju W": "경주 한국수력원자력",
  "Hwacheon KSPO W": "화천 KSPO",
  "Incheon Red Angels": "인천 현대제철 레드엔젤스",
  "Naegohyang W": "내고향",
  "Seoul W": "서울시청",
  "Suwon FMC": "수원 FMC",

  // 프리메이라리가 디비시온 (아르헨티나/남미)
  "Boca Juniors": "보카 주니어스",
  "River Plate": "리버 플레이트",
  "Atletico Nacional": "아틀레티코 나시오날",
  "Deportivo Maipu": "데포르티보 마이푸",
  "Club Nacional": "나시오날",
  "Penarol": "페냐롤",
  "Cerro Porteno": "세로 포르테뇨",
  "LDU de Quito": "LDU 키토",
  "Universitario": "우니베르시타리오",
  "Olimpia": "올림피아",
  "Libertad Asuncion": "리베르타드",
  "Always Ready": "올웨이스 레디",
  "Bolivar": "볼리바르",
  "Bolívar": "볼리바르",
  "Coquimbo Unido": "코키보 우니도",
  "Cusco": "쿠스코 FC",
  "Palmeiras": "팔메이라스",
  "Independ. Rivadavia": "인디펜디엔테 리바다비아",
  "Independiente Rivadavia": "인디펜디엔테 리바다비아",
  "Alianza Atletico": "알리안자 아틀레티코",
  "Macara": "마카라",  
  "Chico": "보야카 치코",
  "Chico FC": "보야카 치코",
  "Deportivo Pasto": "데포르티보 파스토",
  "Bucaramanga": "부카라망가",
  "Club Tijuana": "클럽 티후아나",
  "Club America": "클럽 아메리카",
  "Once Caldas": "온세 칼다스",
  "Envigado": "엔비가도",
  "Cucuta": "쿠쿠타",
  "Fortaleza FC": "포르탈레자 FC",
  "Leones FC": "레오네스 FC",

  // 프리미어십 (스코틀랜드)
  "Aberdeen": "애버딘",
  "Celtic": "셀틱",
  "Dundee": "던디 유나이티드",
  "Dundee Utd": "던디 유나이티드",
  "Dundee United": "던디 유나이티드",
  "Dundee FC": "던디 유나이티드", 
  "Dunfermline": "던퍼믈린",
  "Falkirk": "팰커크",
  "Heart Of Midlothian": "하트 오브 미들로디언",
  "Hibernian": "하이버니언",
  "Kilmarnock": "킬마녹",
  "Larne": "란 FC",
  "Livingston": "리빙스턴",
  "Motherwell": "마더웰",
  "Partick": "파틱 시슬",
  "Rangers": "레인저스",
  "Ross County": "로스 카운티",
  "ST Johnstone": "세인트 존스턴",
  "St. Johnstone": "세인트 존스턴",
  "ST Mirren": "세인트 미렌",
  "St. Mirren": "세인트 미렌",

  // 챔피언십 (잉글랜드 2부)
  "Birmingham": "버밍엄 시티",
  "Blackburn": "블랙번 로버스",
  "Bristol City": "브리스톨 시티",
  "Cardiff": "카디프 시티",
  "Charlton": "찰튼 애슬레틱",
  "Derby": "더비 카운티",
  "Leicester": "레스터 시티",
  "Middlesbrough": "미들즈브러",
  "Millwall": "밀월",
  "Norwich": "노리치 시티",
  "Oxford United": "옥스퍼드 유나이티드",
  "Portsmouth": "포츠머스",
  "Preston": "프레스턴 노스엔드",
  "QPR": "퀸즈 파크 레인저스",
  "Sheffield Utd": "셰필드 유나이티드",
  "Sheff Utd": "셰필드 유나이티드",
  "Sheffield Wednesday": "셰필드 웬즈데이",
  "Southampton": "사우샘프턴",
  "Stoke City": "스토크 시티",
  "Stoke": "스토크 시티",
  "Swansea": "스완지 시티",
  "Watford": "왓퍼드",
  "West Brom": "웨스트 브롬위치 알비온",
  "Wrexham": "렉섬",

  // 리그원 (잉글랜드 3부)
  "Blackpool": "블랙풀",
  "Bolton": "볼턴 원더러스",
  "Bradford": "브래드퍼드 시티",
  "Burton Albion": "버튼 알비온",
  "Exeter City": "엑서터 시티",
  "Huddersfield": "허더즈필드 타운",
  "Lincoln": "링컨 시티",
  "Luton": "루턴 타운",
  "Mansfield Town": "맨스필드 타운",
  "Northampton": "노샘프턴 타운",
  "Peterborough": "피터버러 유나이티드",
  "Plymouth": "플리머스 아길",
  "Reading": "레딩",
  "Rotherham": "로더럼 유나이티드",
  "Stockport County": "스톡포트 카운티",
  "Stevenage": "스티브니지",
  "Wigan": "위건 애슬레틱",
  "Wycombe": "위컴 원더러스",

  // 리가 I (루마니아)
  "AFC Hermannstadt": "헤르만슈타트",
  "CFR 1907 Cluj": "CFR 클루지",
  "CFR Cluj": "CFR 클루지",
  "Chindia Targoviste": "친디아 트르고비슈테",
  "Csikszereda": "치크세레다",
  "Dinamo Bucuresti": "디나모 부쿠레슈티",
  "FCSB": "FCSB",
  "Farul Constanta": "파룰 콘스탄차",
  "FC Botosani": "FC 보토샤니",
  "FC Voluntari": "FC 볼룬타리",
  "Metaloglobus": "메탈로글로부스",
  "Otelul": "오첼룰 갈라치",
  "Oţelul": "오첼룰 갈라치",
  "Petrolul Ploiesti": "페트롤룰 플로이에슈티",
  "Rapid": "라피드 부쿠레슈티",
  "Unirea Slobozia": "우니레아 슬로보지아",
  "Universitatea Cluj": "우니베르시타테아 클루지",
  "Universitatea Craiova": "Univ 크라이오바",

  //러시아
  "Baltika": "FC 발티카 칼리닌그라드",
  "CSKA Moscow": "CSFA 모스크바",
  "Dynamo": "디나모 모스크바",
  "Krylia Sovetov": "크릴리야 소베토프 사마라",
  "Fakel": "FC 파켈 보로네시",
  "Spartak Moscow": "스파르타크 모스크바",


  // HNL (크로아티아)
  "Dinamo Zagreb": "디나모 자그레브",
  "HNK Gorica": "HNK 고리차",
  "HNK Hajduk Split": "하이두크 스플리트",
  "HNK Rijeka": "HNK 리예카",
  "Rijeka": "HNK 리예카", 
  "Istra 1961": "이스트라 1961",
  "NK Lokomotiva Zagreb": "NK 로코모티바 자그레브",
  "NK Osijek": "NK 오시예크",
  "NK Slaven Belupo": "NK 슬라벤 벨루포",
  "NK Varazdin": "NK 바라주딘",

  // Erovnuli Liga (조지아)
  "Dila": "딜라 고리",
  "Dila Gori": "딜라 고리",
  "Dinamo Batumi": "디나모 바투미",
  "Dinamo Tbilisi": "디나모 트빌리시",
  "Gagra": "가그라",
  "Meshakhte": "마사크테 트빌리시",
  "Rustavi": "루스타비",
  "Saburtalo": "사부르탈로",
  "Samgurali": "삼구랄리",
  "Spaeri": "스파에리",
  "Torpedo Kutaisi": "토르페도 쿠타이시",

  // V.League (베트남)
  "Binh Duong": "빈즈엉",
  "Công An Nhân Dân": "하노이 폴리스",
  "Da Nang": "다낭",
  "Ha Noi": "하노이 FC",
  "Hai Phong": "하이퐁",
  "Ho Chi Minh": "호치민 시티",
  "Hoang Anh Gia Lai": "황아잉지아라이",
  "Nam Dinh": "남딘",
  "Pho Hien": "포히엔",
  "Phu Dong": "푸동",
  "Song Lam Nghe An": "송람응에안",
  "Thanh Hóa": "탄호아",
  "Viettel": "비엣텔",
  "Hồng Lĩnh Hà Tĩnh": "홍린 하틴",

  // Taiwan Football Premier League (대만)
  "AC Taipei": "AC 타이페이",
  "Hang Yuen": "항유엔",
  "Ming Chuan University": "밍촨대학교",
  "Taichung Futuro": "타이중 푸투로",
  "Taichung Rock FC": "타이중 록 FC",
  "Tainan City": "타이난 시티",
  "Taipower": "대만전력",
  "Tatung": "래퍼드 캣 FC",

  // 베이직 국가대표 (Friendlies 경유)
  "South Korea": "대한민국",
  "Korea Republic U23": "대한민국 U23",
  "Japan": "일본",
  "China": "중국",
  "China PR U23": "중국 U23",
  "Australia": "호주",
  "France": "프랑스",
  "Germany": "독일",
  "Spain": "스페인",
  "Algeria": "알제리",
  "Algeria W": "알제리",
  "Jordan": "요르단",
  "Jordan W": "요르단",
  "FYR Macedonia": "북마케도니아",
  "Nicaragua": "니카라과",
  "Congo DR": "콩고 민주공화국",
  "Congo DR W": "콩고 민주공화국",
  "Ghana": "가나",
  "Ghana W": "가나",
  "Panama": "파나마",
  "Panama W": "파나마",
  "Dominican Republic W": "도미니카 공화국",
  "Dominican Republic": "도미니카 공화국",
  "USA W": "미국",
  "Canada W": "캐나다",
  "Netherlands W": "네덜란드",
  "Czech Republic W": "체코",
  "Italy W": "이탈리아",
  "Germany W": "독일",
  "China W": "중국",
  "Bulgaria W": "불가리아",
  "Bulgaria": "불가리아",
  "Poland W": "폴란드",
  "Poland": "폴란드",
  "Japan W": "일본",
  "France W": "프랑스",
  "Brazil W": "브라질",
  "Thailand W": "태국",
  "Thailand": "태국",
  "Ukraine W": "우크라이나",
  "Turkey W": "튀르키예",
  "Belgium W": "벨기에",
  "Spain W": "스페인",
  "Montenegro": "몬테네그로",
  "Montenegro W": "몬테네그로",
  "Cape Verde Islands": "카보베르데",
  "Cape Verde": "카보베르데",
  "Italy": "이탈리아",
  "Portugal": "포르투갈",
  "Portugal W": "포르투갈",
  "Netherlands": "네덜란드",
  "Senegal": "세네갈",
  "Senegal W": "세네갈",
  "New Zealand": "뉴질랜드",
  "New Zealand W": "뉴질랜드",
  "Iraq": "이라크",
  "Iraq W": "이라크",
  "Malta W": "몰타",
  "Malta": "몰타",
  "Northern Ireland W": "북아일랜드",
  "Russia W": "러시아",
  "Costa Rica": "코스타리카",
  "Costa Rica W": "코스타리카",
  "Bolivia": "볼리비아",
  "Bolivia W": "볼리비아",
  "Libya": "리비아",
  "Venezuela": "베네수엘라",
  "Nigeria": "나이지리아",
  "Nigeria W": "나이지리아",
  "Chile": "칠레",
  "Chile W": "칠레",
  "Andorra": "안도라",
  "Andorra W": "안도라",
  "Honduras": "온두라스",
  "Honduras W": "온두라스",
  "World Cup": "FIFA 월드컵",
  "Bermuda": "버뮤다",
  "Venezuela W": "베네수엘라",
  "Belgium": "벨기에",
  "Egypt": "이집트",
  "Ivory Coast": "코트디부아르",
  "Ecuador": "에콰도르",
  "Argentina": "아르헨티나",
  "Brazil": "브라질",
  "Serbia": "세르비아",
  "Serbia W": "세르비아",
  "Mexico": "멕시코",
  "South Africa": "남아프리카공화국",
  "Colombia": "콜롬비아",
  "Saudi Arabia": "사우디아라비아",
  "Uruguay": "우루과이",
  "Haiti": "아이티",
  "Iran": "이란",
  "Japan U19": "일본 U19",
  "Japan U21": "일본 U21",
  "Rep. Of Ireland": "아일랜드",
  "Ireland": "아일랜드",
  "Ireland W": "아일랜드",
  "Republic of Ireland U21": "아일랜드 U21",
  "Northern Ireland": "북아일랜드",
  "Uzbekistan": "우즈베키스탄",
  "Uzbekistan W": "우즈베키스탄",
  "Wales": "웨일스",
  "England": "잉글랜드",
  "Scotland": "스코틀랜드",
  "Turkey": "튀르키예",
  "Türkiye": "튀르키예",
  "Georgia W": "조지아",
  "Georgia": "조지아",
  "Switzerland W": "스위스",
  "North Macedonia W": "북마케도니아",
  "North Macedonia": "북마케도니아",
  "Albania W": "알바니아",
  "Albania": "알바니아",
  "Croatia": "크로아티아",
  "Croatia W": "크로아티아",
  "Romania W": "루마니아",
  "Ukraine": "우크라이나",
  "Curaçao": "퀴라소",
  "Curaçao W": "퀴라소",
  "Cuba": "쿠바",
  "Kosovo": "코소보",
  "Kosovo W": "코소보",
  "Greece W": "그리스",
  "Greece": "그리스",
  "Estonia W": "에스토니아",
  "Estonia": "에스토니아",
  "Hungary W": "헝가리",
  "Israel": "이스라엘",
  "Israel W": "이스라엘",
  "Bosnia-Herzegovina W": "보스니아 헤르체고비나",
  "Bosnia & Herzegovina": "보스니아 헤르체고비나",
  "Bosnia & Herzegovina W": "보스니아 헤르체고비나",
  "Azerbaijan": "아제르바이잔",
  "Azerbaijan W": "아제르바이잔",
  "Romania": "루마니아",
  "Iceland W": "아이슬란드",
  "Iceland": "아이슬란드",
  "Slovenia W": "슬로베니아",
  "Luxembourg": "룩셈부르크",
  "Luxembourg W": "룩셈부르크",
  "Philippines": "필리핀",
  "Guam": "괌",
  "Kuwait": "쿠웨이트",


  // 코파 리베르타도레스 / 수다메리카나 주요팀
  "Atletico Mineiro": "아틀레티코 미네이루",
  "Atletico-MG": "아틀레티코 미네이루",
  "Atletico MG": "아틀레티코 미네이루",
  "Sporting Cristal": "스포르팅 크리스탈",
  "Millonarios": "미요나리오스",
  "Deportes Tolima": "데포르테스 톨리마",
  "Tolima": "데포르테스 톨리마",
  "Independiente del Valle": "인디펜디엔테 델 바예",
  "Santa Fe": "산타페",
  "Junior": "주니오르 데 바란키야",
  "Independiente Medellin": "인데펜디엔테 메데인",
  "Deportivo Cali": "데포르티보 칼리",
  "Deportivo Pereira": "데포르티보 페레이라",
  "Aguilas Doradas": "아귈라스 페레이라",
  "America de Cali": "아메리카 데 칼리",
  "Flamengo": "플라멩고",
  "Fluminense": "플루미넨세",
  "Botafogo": "보타포고",
  "Botafogo RJ": "보타포고",
  "Gremio": "그레미우",
  "Internacional": "인테르나시오나우",
  "Vasco DA Gama": "바스코 다 가마",
  "RB Bragantino": "RB 브라간치누",
  "Corinthians": "코린치안스",
  "Atletico Paranaense": "아틀레티코 파라나엔세",
  "San Lorenzo": "산 로렌소",
  "Racing Club": "레이싱 클럽",
  "Rosario Central": "로사리오 센트랄",
  "Estudiantes L.P.": "에스투디안테스",
  "Estudiantes": "에스투디안테스",
  "Universidad Catolica": "Univ. 카톨리카",
  "Tigre": "티그레",
  "Jaguares": "하우가레스 코르도바",
  "CD Jaguares": "하우가레스 코르도바",
  "Popayan": "우니베르시타리오 포파얀",

  // 프리미어 디비전 (아일랜드)
  "Bohemians": "보헤미안스",
  "Bohemian FC": "보헤미안스",
  "Derry City": "데리 시티",
  "Drogheda United": "드로에다 유나이티드",
  "Dundalk": "던돌크",
  "Galway United": "골웨이 유나이티드",
  "Shamrock Rovers": "섐록 로버스",
  "Shelbourne": "셸번",
  "Sligo Rovers": "슬라이고 로버스",
  "St Patrick's Athl.": "세인트 패트릭스 애슬레틱",
  "Waterford": "워터퍼드",
  "Cliftonville": "클리프턴빌",
 

  // OFC Pro League (오세아니아)
  "Auckland FC 2": "오클랜드 FC 2",
  "Bula": "불라 FC",
  "Hekari United": "헤카리 유나이티드",
  "Solomon Kings": "솔로몬 킹스",
  "South Island United": "사우스 아일랜드 유나이티드",
  "South Melbourne": "사우스 멜버른",
  "Tahiti United": "타히티 유나이티드",
  "Vanuatu United": "바누아투 유나이티드",

  // PFL (필리핀)
  "Davao Aguilas": "다바오 아길라스",
  "Dynamic Herb Cebu": "다이나믹 허브 세부",
  "Garelli United": "가렐리 유나이티드",
  "Kaya": "카야 FC",
  "Maharlika": "마하를리카 FC",
  "Manila Digger": "마닐라 디거",
  "Mendiola": "멘디올라",
  "Philippine Army": "필리핀 육군",
  "Stallion": "스탤리온 라구나",
  "Taguig": "타귀그",
  "Tuloy": "툴로이",

  // AFC U17
  "Korea Republic U17": "대한민국 U17",
  "Korea DPR U17": "북한 U17",
  "Japan U17": "일본 U17",
  "China PR U17": "중국 U17",
  "Saudi Arabia U17": "사우디 U17",
  "Australia U17": "호주 U17",
  "India U17": "인도 U17",
  "Indonesia U17": "인도네시아 U17",
  "Myanmar U17": "미얀마 U17",
  "Qatar U17": "카타르 U17",
  "Tajikistan U17": "타지키스탄 U17",
  "Thailand U17": "태국 U17",
  "Uzbekistan U17": "우즈베키스탄 U17",
  "Vietnam U17": "베트남 U17",
  "UAE U17": "아랍에미리트 U17",
  "United Arab Emirates U17": "아랍에미리트 U17",

  // ASEAN Championship
  "Brunei": "브루나이",
  "Timor-Leste": "동티모르",
  "Laos": "라오스",
  "Myanmar": "미얀마",
  "Malaysia": "말레이시아",
  "Singapore": "싱가포르",
  "Cambodia": "캄보디아",
  "Vietnam": "베트남",
  "Nepal": "네팔",
  "Turkmenistan": "투르크메니스탄",
  "Sri Lanka": "스리랑카",
  "Indonesia": "인도네시아",
  "Mongolia": "몽골",
  "Maldives": "몰디브",
  "Bhutan": "부탄",
  "Hong Kong": "홍콩",
  "St. Kitts and Nevis": "세인트키츠 네비스",
  "Mozambique": "모잠비크",

  // 기타 주요 단일팀
  "CONCACAF Champions League": "CONCACAF 챔피언스리그",
  "Tigres UANL": "티그레스 UANL",
  "Toluca": "톨루카",
  "Al-Ettifaq": "알 에티파크",
  "Al-Hilal Saudi FC": "알힐랄",
  "Al Hilal": "알힐랄",
  "Al-Faisaly": "알 파이살리",
  "Al-Nassr": "알나스르",
  "Al-Nasr SC": "알나스르",
  "Al Nassr FC": "알나스르",
  "Al-Ittihad FC": "알이티하드",
  "Al Ittihad": "알이티하드",
  "Al Diriyah": "알 드라이흐",
  "Al-Diriyah": "알 드라이흐",
  "Al Ittihad Kalba": "알이티하드 칼바",

  "Al-Ittihad Kalba": "알이티하드 칼바",

  "Al Ahli": "알아흘리",
  "Al-Ahli Jeddah": "알아흘리 제다",
  "Al-Fayha": "알파이하",
  "Al Fateh FC": "알파테흐",
  "Al-Fateh": "알파테흐",
  "Al-Hazm": "알하즘",
  "Al Hazem": "알하즘",
  "Abha": "아바",
  "Al-Raed": "알라에드",
  "Al-Qadisiyah FC": "알카디시야",
  "Al Qadsiah": "알카디시야",
  "Damac": "다마크",
  "NEOM": "네옴 SC",
  "Neom SC": "네옴 SC",
  "Al Khaleej Saihat": "알칼레지 사이핫",
  "Al-Khaleej Saihat": "알칼레지 사이핫",
  "Al Khaleej": "알칼리즈",
  "Al-Khaleej": "알칼리즈",
  "Al Kholood": "알콜루드",
  "Al-Kholood": "알콜루드",
  "Al Najma": "알나즈마",
  "Al-Najma": "알나즈마",
  "Al Okhdood": "알오크후드",
  "Al-Okhdood": "알오크후드",
  "Al Riyadh": "알리야드",
  "Al-Riyadh": "알리야드",
  "Al Shabab": "알샤밥",
  "Al-Shabab": "알샤밥",
  "Sharjah Cultural Club": "알샤르자",
  "Al Taawon": "알타아원",
  "Al-Taawoun": "알타아원",
  "Shabab Al Ahli Dubai": "샤밥 알아흘리 두바이",
  "Shabab Al-Ahli Dubai FC": "샤밥 알아흘리 두바이",
  "Sharjah FC": "샤르자 FC",
  "Al Ain": "알아인",
  "Al-Ain": "알아인",
  "Al Wahda FC": "알와흐다",
  "Al-Wahda": "알와흐다",
  "Ajman": "아지만",
  "Al Jazira": "알자지라",
  "Al-Jazira": "알자지라",
  "Al-Dhafra": "알다프라",
  "Al-Wasl FC": "알와슬",
  "Baniyas SC": "바니야스",
  "Baniyas": "바니야스",
  "Dibba Al-Fujairah": "디바 알후자이라",
  "Khorfakkan": "코르파칸",
  "Meizhou Kejia": "메이저우 하카",
  "Qingdao Jonoon": "칭다오 하이뉴",
  "Qingdao Hainiu": "칭다오 하이뉴",
  "Shenyang Urban": "랴오닝 선양",
  "Liaoning Tieren": "랴오닝 선양",
  "Wuhan Three Towns": "우한 쓰리 타운즈",
  "Toledo Mud Hens": "톨레도 머드헨스",
  "Deportivo Maldonado": "데포르티보 말도나도",
  "Albion FC": "알비온 FC",
  "Liverpool Montevideo": "리버풀 몬테비데오",
  "Cerro": "세로",
  "Boston River": "보스톤 리베르",
  "Racing Montevideo": "라싱 몬테비데오",
  "Racing": "라싱 몬테비데오",
  "Hatta": "하타",
  "Hatta SC": "하타",

  //스위스
  "Lausanne": "로잔 스포르",
  "Grasshoppers": "그라스호퍼",
  "Grasshopper": "그라스호퍼",
  "FC Aarau": "FC 아라우",
  "Servette FC": "세르베트",
  "Servette": "세르베트",
  "FC Basel 1893": "FC 바젤 1893",
  "Basel": "FC 바젤 1893",
  "Stade Nyonnais": "스타드 니옹",
  "FC Luzern": "FC 루체른",
  "Luzern": "FC 루체른",

  //UEFA
  "Ararat-Armenia": "아라라트 아르메니아",
  "Ararat Armenia": "아라라트 아르메니아",
  "Riga": "리가 FC",
  "Riga FC": "리가 FC",
  "Borac Banja Luka": "보라츠",
  "Levski Sofia": "레프스키 소피아",
  "Floriana": "플로리아나",
  "Kauno Žalgiris": "FK 카우노 잘기리스",
  "Drita": "드리타",
  "KI Klaksvik": "클락스비크",
  "Klaksvik": "클락스비크",
  "Atert Bissen": "FC 아테르트",
  "Lincoln Red Imps FC": "링컨 레드임프스",
  "Inter Club d'Escaldes": "인터 클럽 드 에스칼데스",
  "Sabah FA": "사바 FA",
  "Sabah FK": "사바 FA",
  "The New Saints": "더 뉴 세인츠 FC",
  "TNS": "더 뉴 세인츠 FC",
  "Tre Fiori": "트레 피오리",
  "Vardar Skopje": "FK 바르다르",
  "FK Vardar Skopje": "FK 바르다르",
  "Vikingur Reykjavik": "바이킹어 레이캬비크",
  "Gyori ETO FC": "죄르 ETO",
  "Györi ETO": "죄르 ETO",
  "Bate Borisov": "BATE 보리소프",
  "AF Elbasani": "AF 엘바사니",
  "La Fiorita": "라 피오리타",
  "UNA Strassen": "UNA 슈트라센",
  "Flora Tallinn": "플로라 탈린",
  "Tallinna FC Flora": "플로라 탈린",
  "Kairat Almaty": "카이라트",
  "Sutjeska": "FK수체스카",
  "ML Vitebsk": "ML 비테프스크",
  "Petrocub": "페트로쿱",
  "Egnatia Rrogozhinë": "에그나티아",
  "Egnatia": "에그나티아",
  "GAP Connah S Quay FC": "코나스 퀘이",
  "Ballkani": "발카니",
  "Atlètic Club d'Escaldes": "아틀레틱 에스칼데스",
  "Atletic Escaldes": "아틀레틱 에스칼데스",
  "Alashkert": "알라쉬커트",
  "St Joseph S Fc": "세인트 조지프스",
  "FC Levadia Tallinn": "탈린나 FCI 레바디아",
  "FK Liepaja": "리에파야",
  "Dečić": "데치치",
  "Virtus": "SS 비르투스",
  "Dinamo Tirana": "FC 디나모 시티",
  "FC Dinamo City": "FC 디나모 시티",
  "FC Astana": "아스타나",
  "Dinamo Minsk": "디나모 민스크",
  "Sileks": "실렉스",
  "Europa": "유로파",
  "Shkendija": "스켄디야",
  "KF Shkendija": "스켄디야",
  "FK Sarajevo": "FK 사라예보",
  "Glentoran": "글렌토런",
  "Rīgas FS": "리가스",
  "Hegelmann Litauen": "FC 헤겔만",
  "Paide": "파에데 린나메스코드",
  "Kalju Nomme": "넘메 칼리우",

  "Linfield": "린필드",
  "Marsaxlokk": "마르사실로크",
  "Pyunik Yerevan": "퓨니크",
  "NSI Runavik": "루나비크",
  "Hamrun Spartans": "함룬",
  "Penybont": "페니본트",
  "FC Santa Coloma": "FC 산타콜로마",
  "Petrovac": "OFK 페트로바치",
  "FK Zalgiris Vilnius": "잘기리스 빌뉴스",
  "Zalgiris Vilnius": "잘기리스 빌뉴스",
  "Velež": "FK 벨레주 모스타르",
  "Milsami Orhei": "밀사미 오르헤이",
  "Stjarnan": "스탸르난",
  "Vikingur Gota": "바이킹어",
  "Vllaznia Shkodër": "KF 블라즈니아",
  "CSKA Sofia": "CSKA 소피아",
  "Dynamo Kyiv": "디나모 키예프",
  "Žilina": "질리나",
  "Qarabag": "카라바흐",
  "Qarabag FK": "카라바흐",
  "Sheriff Tiraspol": "FC 셰리프",
  "FC Sheriff": "FC 셰리프",
  "Aluminij": "알루미니",
  "Vojvodina": "보이보디나",
  "Ferencvarosi TC": "페렌츠바로시",
  "Ferencvaros": "페렌츠바로시",
  "Defensor Sporting": "데펜소르 스포르팅",
  "Cerro Largo": "세로 라르고",
  "O’Higgins": "오히긴스",
  "Kisvarda FC": "키스바르다",
  "Debreceni VSC": "데브레체니 VSC",
  "KA Akureyri": "KA 아쿠레이리",
  "Breidablik": "브레이다블리크",
  "Fram Reykjavik": "프람",
  "Malisheva": "말리셰바",
  "Gjilani": "질리니",
  "Dukagjini": "두카그지니",
  "Prishtina": "프리슈티나",
  "Panevėžys": "파네베지스",
  "Džiugas Telšiai": "지우가스 텔샤이",
  "TransINVEST Vilnius": "트란신베스트",
  "Gzira United": "그리자 유나이티드",
  "Kuressaare": "FC 쿠레사이레",
  "Vaprus": "패르누 JK 바프루스",
  "Carroi": "CE 카로이",
  "Struga": "스트루가",
  "Stranraer": "스트랜라 FC",
  "Dungannon Swifts": "던개넌 스위프트",
  "Radnik Surdulica": "FK 라드니크 수르둘리차",
  "Botev Vratsa": "보테브 브라트사",
  "Etar Veliko Tarnovo": "에타르 벨리코 타르노보",
  "Akademik Svishtov": "아카데믹 스비스토프",
  "Akhmat": "아흐마트 그로즈니",
  "Radnik Bijeljina": "라드니크 비옐리나",
  "FS Jelgava": "FS 옐가바",
  "Auda": "FK 아우다",
  "BFC Daugavpils": "BFC 다우가프필스",
  "Gandzasar": "간자사르",
  "FC Noah": "FC 노아",
  "Turan": "투란 토브스 IK",
  "Olimpija Ljubljana": "올림피야 류블랴나",
  "NK Olimpija Ljubljana": "올림피야 류블랴나",
  "Arges Pitesti": "FC 아르제슈 피테슈티",
  "FC Argeș Pitești": "FC 아르제슈 피테슈티",
  "Mons Calpe": "몬스 칼페",
  "Mornar": "모르나르",
  "FC Differdange 03": "디페르댕 03",
  "Caernarfon Town": "케르나폰 타운",
  "Caernarfon": "케르나폰 타운",
  "Yelimay Semey": "옐리마이 세미",
  "Queen of the South": "퀸 오브 더 사우스",
  "Ordino": "FC 오르디노",
  "UE Santa Coloma": "UE 산타 콜로마",
  "Nõmme Kalju": "넘메 칼리우",

  "Harju Jalgpallikool": "하르주JK",
  "Dundela": "던델라",
  "Zorya Luhansk": "조라 루한시크",
  "Celje": "NK 첼레",
  "Neman Grodno": "네만 르로드노",
  "Gomel": "FC 호멜",
  "Sumqayıt": "숨가이트",
  "Mil Mugan FK": "밀 무간 FK",
  "Qabala": "FK 카발라",
  "Kyzyl-Zhar": "키질자르",
  "Atyrau": "FC 아티리우",
  "Ordabasy": "FC 오다바시",
  "FK Partizan": "FK 파르티잔",
  "Partizan Beograd": "FK 파르티잔",
  "Rače": "NK 라체",
  "Marek": "마렉",
  "Polessya": "FC 폴리샤 지토미르",
  "Polissya Zhytomyr": "FC 폴리샤 지토미르",
  "Nyiregyhaza": "니레지하자",
  "Ujpest": "우이페슈트",
  "Wieczysta Kraków": "KS 위치스타 크라쿠프",
  "Fylkir": "필키르",
  "Grindavík": "UMF 그린다비크",
  "Pardubice": "파르두비체",
  "Odra Opole": "오드라 오폴레",
  "Opava": "오파바",
  "LNZ Cherkasy": "하이두크 스플리트",
  "Hajduk Split": "하이두크 스플리트",
  "Rodange 91": "FC 로당주 91",
  "Racing FC Union Luxembourg": "라싱FC 유니온 룩셈부르크",
  "Jeunesse Canach": "죄네스 카나흐",
  "Uta Arad": "UTA 아라드",
  "FC Bacau": "FCM 바카우",  
  "Banga": "방가 가르그즈다이",
  "Slovan Liberec": "슬로반 리베레츠",
  "FK Košice": "FK 코시체",
  "Corvinul Hunedoara": "FC 코르비눌 후네도아라",
  "Koper": "코페르",
  "Zbrojovka Brno": "FC즈브로요프카 브르노",
  "Aarhus": "오르후스",
  "Fenerbahçe": "페네르바흐체",

  "FC Thun": "FC 툰",
  "Thun": "FC 툰",
  "Slovan Bratislava": "슬로반 브라티슬라바",
  "FK Crvena Zvezda": "츠르베나 즈베즈다",
  "Hapoel Beer Sheva": "하포엘 베르셰바",
  "Horsens": "호르센스", // ⚠️ "AC Horsens"와 같은 팀인데 한글 표기가 달라서 통일함(2026-08 감사)
  "Viborg": "비보르",
  "Podbrezová": "포드브레조바",
  "Admira Wacker": "FC 아드미라 바커",
  "Eyüpspor": "에유프스포르",
  "Galatasaray": "갈라타사라이",
  "FC Nordsjaelland": "FC 노르셸란",
  "Nordsjaelland": "FC 노르셸란",
  "Nordsjælland": "FC 노르셸란",
  "Hallescher FC": "할레셔 FC",
  "Kalsdorf": "칼스도르프",
  "Waldhof Mannheim": "SV 발트호프 만하임",
  "FC ST. Gallen": "FC 장트 갈렌",
  "St. Gallen": "FC 장트 갈렌",
  "FC Sion": "FC 시옹",
  "Sion": "FC 시옹",
  "Cork City": "코크 시티",
  "Pafos": "파포스 FC",
  "Pafos FC": "파포스 FC",
  "Puskas Academy": "푸슈카시 아카데미",
  "H&W Welders": "H&W 웰더스",
  "Macva": "FK 마크바 사바크",
  "Zenit": "제니트 상트페테르부르크",
  "SKU Amstetten": "SKU 암슈테텐",
  "FC Copenhagen": "FC 코펜하겐",
  "FC København": "FC 코펜하겐",
  "Thor Akureyri": "토르 아쿠레이리",
  "Maccabi Tel Aviv": "마카비 텔아비브",
  "Omonia Nicosia": "오모니아 니코시아",
  "07 Vestur": "07 베스터",
  "Šiauliai": "FA 샤울랴이",
  "Velazerimi 77": "벨라제리미 77",
  "Labunishta": "FK 라부니슈타",
  "AC Horsens": "호르센스",
  "Spartak Trnava": "스파르타크 트르나바",
  "CSKA 1948": "CSKA 1948 소피아",
  "Beşiktaş": "베식타스 JK",
  "Šamorín": "STK 1914 샤모린",
  "Slovácko": "슬로바츠코",
  "Plzen": "빅토리아 플젠",
  "Maribor": "마리보르",
  "Başakşehir": "이스탄불 바샥셰히르",
  "Neftchi Baku": "PFK 네프치 바쿠",
  "FK Neftchi": "PFK 네프치 바쿠",
  "MTK Budapest": "MTK 부다페스트",
  "Cukaricki": "추카리츠키",
  "Apollon Limassol": "아폴론 리마솔",
  "Apoel Nicosia": "아포엘 니코시아 FC",
  "Beitar Jerusalem": "베이타르 예루살렘",
  "AEK Larnaca": "라르니카",
  "FK Tobol Kostanay": "FK 토볼",
  "Tobol Kostanay": "FK 토볼",
  "Ludogorets": "루도고레츠",
  "Coleraine FC": "콜레인 FC",
  "Coleraine": "콜레인 FC",
  "FC Lugano": "FC 루가노",
  "Lugano": "FC 루가노",
  "Limavady": "리마바디",
  "FC Vaduz": "FC 바두츠",
  "Memmingen": "FC 메밍겐",
  "Rapperswil": "FC 라퍼스필-요나",
  "SC Kriens": "SC 크린스",
  "FC Zurich": "FC 취리히",
  "FC Zürich": "FC 취리히",
  "HB Torshavn": "HB 토르스하운",
  "Paks": "퍽시 FC",
  "Valletta FC": "발레타 FC",
  "Valur Reykjavik": "발루르 레이캬비크",
  "Valur": "발루르",
  "Zrinjski": "HSK 즈리니스키 모스타르",
  "FK Jablonec": "야블로네츠",
  "Jablonec": "야블로네츠",
  "Zimbru": "짐브루 키시너우",
  "Bravo": "NK 브라보",
  "FC Midtjylland": "미트윌란",
  "Hradec Králové": "흐라덱 크라로베",
  "Hradec Kralove": "흐라덱 크라로베",
  "Yverdon Sport": "이베르동스포르",
  "Neuchatel Xamax FC": "뇌샤텔 크사막스 FCS",
  "Étoile Carouge": "에투알 카루주",
  "Radnicki NIS": "FK 라드니츠키 니슈",
  "Slavia Praha": "슬라비아 프라하",
  "Sigma Olomouc": "SK 시그마 올로모우츠",
  "Raith Rovers": "레이스 로버스",
  "Carrick Rangers": "C.레인저스",
  "Portadown": "포터다운",
  "Ballymena United": "밸리미나 유나이티드",
  "Ballinamallard United": "발리나말라드",
  "Glenavon": "글레나본",
  "Glenavon FC": "글레나본",
  "Warrenpoint Town": "워렌포인트 타운",
  "Maritimo": "마리타무",
  
  //중국축구
  "Changchun Yatai": "창춘 야타이",
  "Dalian Huayi": "다롄 쿤 시티",
  "Hebei Kungfu": "스자좡 쿵후",
  "Suzhou Dongwu": "쑤저우 동우",
  "Nanjing City": "난징 시티",
  "Ningbo Professional": "닝보 프로페셔널",
  "Heilongjiang Lava Spring": "헤이룽장 훠샨밍취안",
  "Guangzhou E-Power": "광둥 GZ-파워",
  "Wuxi Wugou": "우시 우고",
  "Sichuan Jiuniu": "선전 신청펑",
  "Shenzhen Peng City": "선전 신청펑",
  "Chongqing Tongliang Long": "충칭 통량룽",
  "Beijing Guoan": "베이징 궈안",
  "Shandong Luneng": "산둥 타이산",
  "Shandong Taishan": "산둥 타이산",
  "Henan Jianye": "허난 FC",
  "Henan FC": "허난 FC",
  "SHANGHAI SIPG": "상하이 하이강",
  "Shanghai Port": "상하이 하이강",
  "Tianjin Teda": "텐진 진먼후",
  "Tianjin Jinmen Tiger": "텐진 진먼후",
  "Hangzhou Greentown": "저장 뤼청",
  "Zhejiang Professional": "저장 뤼청",
  "Dalian Zhixing": "다롄 잉보 FC",
  "Dalian Yingbo": "다롄 잉보 FC",
  "Shanghai Shenhua": "상하이 선화",
  "Yunnan Yukun": "윈난 유쿤",
  "Qingdao Youth Island": "칭다오 FC",
  "Qingdao West Coast": "칭다오 FC",
  "Shaanxi Union": "산시 유니온",
  "Shenzhen Juniors": "선전 주니어스",
  "Nantong Zhiyun": "난퉁 지윈",
  "Chengdu Better City": "청두 룽청",
  "Chengdu Rongcheng FC": "청두 룽청",
  "Zhejiang FC": "저장 FC",
  "Jiangxi Liansheng": "장시 롄성",
  "Rizhao Yuqi": "리조우 위치",
  "Dalian Kewei": "다롄 케웨이"

};

export default TEAM_NAME_MAP;